### ISSUE TITLE
webpack 4 compatibility

### ISSUE THREAD

**Issue by lmmarsano** [reshape/loader#33]
With the environment
```ShellSession
$ npm ls --depth 0 webpack reshape-loader
/home/luism/project/journal
├── reshape-loader@1.1.0 
└── webpack@4.2.0
```
`webpack -d` outputs the error
```
Module build failed: TypeError: this._compiler.applyPlugins is not a function
    at Object.module.exports (/home/luism/project/journal/node_modules/reshape-loader/lib/index.js:26:18)
```
Looking at
- the line
  https://github.com/reshape/loader/blob/5b49bcb765132c01da709837c110db1fa303eb40/lib/index.js#L25-L26
- [documentation for custom plugin hooks](//webpack.js.org/api/plugins/#custom-hooks)
- and the webpack source code
  https://github.com/webpack/webpack/blob/d668a23fdc69c61ab80ec8db89a5b49778559534/lib/Compilation.js#L1833-L1838

I gather this may have something to do with method `applyPlugins` deprecation.
Any plans to support webpack 4?
# Steps to Reproduce
```sh
git clone https://github.com/reshape/loader.git
cd loader/
npm install -D webpack@latest
npm install
npm test
```
The first test fails with the same error.
```
  basic

  Rejected promise returned by test. Reason:

  {
    err: [
      ModuleBuildError {
        dependencies: Array [ … ],
        error: TypeError { … },
        message: `Module build failed: TypeError: this._compiler.applyPlugins is not a function␊
            at Object.module.exports (/home/luism/project/loader/lib/index.js:8:39)`,
        module: NormalModule { … },
        origin: NormalModule { … },
      },
    ],
    outputPath: '/home/luism/project/loader/test/fixtures/basic/bundle.js',
  }
```

**Comment by jescalan** [comment]
Hi there! Reshape-loader is not compatible with webpack 4 at all. Webpack 4 is massively breaking for just about every loader and plugin, it's an incredible amount of work to upgrade deeply integrated loaders like this, webpack still does not have an official migration guide, and I have a ton of work on my plate, so I haven't been able to get to it.

If you are interested in helping out with getting reshape-loader to webpack 4 compatibility, that would be amazing, and I'd be happy to advise best I can.
